version: "3"

services:
  redis:
    container_name: redis-container
    image: "redis:latest"

  node-app:
    container_name: nodejs-container
    restart: always
    build: .
    ports:
      - 8081:8081
    depends_on:
      - redis
